# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list
    silent: true

  test:
    cmds:
      - go test -v ./...
    silent: true

  bench:
    cmds:
      - go test -bench=. -benchmem ./...
    silent: true

